### ISSUE TITLE
stopProcessGroup throws UnexpectedValueException

### ISSUE THREAD

**Issue by wotek** [indigophp-archive/supervisor#12]
Supervisord version 3.0.0

When calling `stopProcessGroup` it returns an empty response which results in `UnexpectedValueException` being thrown altho processes got stopped.

I'm not sure whether this is an issue of supervisord itself. If so, close this issue if not happy to help solving it.

**Comment by sagikazarmark** [comment]
I am closing this issue for now. If the issue still exists, please open it at https://github.com/supervisorphp/supervisor
