### ISSUE TITLE
Uncaught exception 'Zend\XmlRpc\Client\Exception\FaultException' with message 'BAD_NAME: workers:worker_1' when using stop/start from Process object

### ISSUE THREAD

**Issue by mostonek** [indigophp-archive/supervisor#17]
// returns Process object
$process = $supervisor->getProcess('workers:worker_1');
$process->stop();

generates this:

PHP Fatal error:  Uncaught exception 'Zend\XmlRpc\Client\Exception\FaultException' with message 'BAD_NAME: workers:worker_1' in /home/moston/web/indigophp/vendor/zendframework/zend-xmlrpc/Zend/XmlRpc/Client.php:323
Stack trace:
#0 /home/moston/web/indigophp/vendor/indigophp/supervisor/src/Connector/ZendConnector.php(83): Zend\XmlRpc\Client->call('supervisor.getP...', Array)
#1 /home/moston/web/indigophp/vendor/indigophp/supervisor/src/Process.php(63): Indigo\Supervisor\Connector\ZendConnector->call('supervisor', 'getProcessInfo', Array)
#2 /home/moston/web/indigophp/vendor/indigophp/supervisor/src/Supervisor.php(173): Indigo\Supervisor\Process->__construct('workers:worker_...', Object(Indigo\Supervisor\Connector\ZendConnector))
#3 /home/moston/web/indigophp/test.php(19): Indigo\Supervisor\Supervisor->getProcess('workers:worker_...')
#4 {main}

Next exception 'Indigo\Supervisor\Exception\SupervisorException' with message 'BAD_NAME: workers:worker_1' in /home/moston/web/indigophp/vendor/indigophp/supervisor/src/Connector/ZendCon in /home/moston/web/indigophp/vendor/indigophp/supervisor/src/Connector/ZendConnector.php on line 85

**Comment by sagikazarmark** [comment]
I am closing this issue for now. If the issue still exists, please open it at https://github.com/supervisorphp/supervisor
